apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
  namespace: aurora-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud
  template:
    metadata:
      labels:
        app: fraud
    spec:
      containers:
        - name: fraud
          image: nanachi1027/aurora-fraud:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: CONSUL_HOST
              value: consul
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/fraud
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin