apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: aurora-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: nanachi1027/aurora-notification:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: aurora-config
                  key: SPRING_PROFILES_ACTIVE
            - name: CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: aurora-config
                  key: CONSUL_HOST
            - name: CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: aurora-config
                  key: CONSUL_PORT
            - name: SPRING_DATASOURCE_HOST
              valueFrom:
                configMapKeyRef:
                  name: aurora-config
                  key: POSTGRES_HOST
            - name: SPRING_DATASOURCE_PORT
              valueFrom:
                configMapKeyRef:
                  name: aurora-config
                  key: POSTGRES_PORT
            - name: SPRING_DATASOURCE_DB
              value: notification
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: aurora-config
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: aurora-config
                  key: POSTGRES_PASSWORD
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: aurora-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: aurora-config
                  key: RABBITMQ_PORT
