server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${APP_NAME:apigw}

  cloud:
    consul:
      host: ${CONSUL_HOST:consul-server.default.svc.cluster.local}
      port: ${CONSUL_PORT:8500}

    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/api/v1/customers/**

        - id: fraud
          uri: lb://fraud
          predicates:
            - Path=/api/v1/fraud/**

        - id: notification
          uri: lb://notification
          predicates:
            - Path=/api/v1/notification/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: ${LOG_LEVEL:INFO}