apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
  namespace: aurora-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud
  template:
    metadata:
      labels:
        app: fraud
    spec:
      containers:
        - name: fraud
          image: nanachi1027/aurora-fraud:f58570b3caa4836fa20f43a3d297c4e81ed6976b
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: aurora-config
                  key: SPRING_PROFILES_ACTIVE
            - name: CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: aurora-config
                  key: CONSUL_HOST
            - name: CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: aurora-config
                  key: CONSUL_PORT
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: aurora-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: aurora-config
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: aurora-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: aurora-config
                  key: POSTGRES_PASSWORD
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: aurora-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: aurora-config
                  key: RABBITMQ_PORT