apiVersion: v1
kind: ConfigMap
metadata:
  name: aurora-config
  namespace: aurora-prod
data:
  SPRING_PROFILES_ACTIVE: "prod"
  CONSUL_HOST: "consul.aurora-prod.svc.cluster.local"
  CONSUL_PORT: "8500"
  POSTGRES_HOST: "postgres.aurora-prod.svc.cluster.local"
  POSTGRES_PORT: "5432"
  RABBITMQ_HOST: "rabbitmq.aurora-prod.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  # TODO: refactor into secret in next commit
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "admin"

